### ISSUE TITLE
bug (and fix) for gravity change map

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#100]
When looking at gravity changes between surveys, I get the following error when displaying (clicking on) map:

`Traceback (most recent call last):
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/gui_objects.py", line 945, in plot
    self.points = self.ax.scatter(x, y, c=d, s=200, vmin=clim[0], vmax=clim[1], cmap="RdBu",
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/lib/python3.8/site-packages/cartopy/mpl/geoaxes.py", line 305, in wrapper
    raise ValueError('Invalid transform: Spherical {} '
ValueError: Invalid transform: Spherical scatter is not supported - consider using PlateCarree/RotatedPole.
Aborted (core dumped`

The solution I found was documented [here](https://stackoverflow.com/questions/13657748/contouring-with-cartopy-valueerror-invalid-transform-spherical-contouring-is).

I changed line 945 of file gui:objects.py from
`transform=self.ccrs.Geodetic())`
to
`transform=self.ccrs.PlateCarree())`
and everything was working (after restart of program).

Cheers

**Comment by jkennedy-usgs** [comment]
Thank you for the report, and the fix...I'm pretty sure this is working in my region (southwest US) so maybe it's a function of eastern or southern hemisphere coordinates. I will look into it. I find Cartopy difficult to work with, someday I'd like to swap it out for something else, maybe Leaflet maps in an HTML window, like Metadata Wizard.
