### ISSUE TITLE
loading CG-6 data

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#109]
When choosing to load raw CG-6 data (both .dat and .tsf options), the popping up dialog only shows .csv and .txt files, neither .dat or .tsf files. This was working in previous versions.

work-arround (quick and dirty):

Rename file ending to .csv and use appropiate loading option.

**Comment by jkennedy-usgs** [comment]
Added csv, txt, dat, and tsf file file filter to all open dialogs.
