### ISSUE TITLE
QResource system for icons/etc.

### ISSUE THREAD

**Issue by mfitzp** [jkennedy-usgs/sgp-gsadjust#65]
Currently icons/etc. are specified using image file paths relative to the application. Qt includes a resource system for managing external data files, to use them you create a definition file (.qrc) and then "compile" your resources into Python code (bytestring).

`QtGui.QIcon('./gsadjust/resources/g.png')`
....becomes...
`QtGui.QIcon(':/icons/g.png')` 

It's complete optional, but can simplify things when it comes to packaging. If you have a look [in this tutorial](https://www.learnpyqt.com/courses/packaging-and-distribution/packaging-pyqt5-pyside2-applications-windows-pyinstaller/) for "Qt Resources" it explains it a bit.

**Comment by jkennedy-usgs** [comment]
Transitioned all icons to Qresources.
