### ISSUE TITLE
Installing / starting gsadjust gives error

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#8]
I cloned this repository and tried once with the recommended miniconda-way of running GSadjust and once with a "manual" python call. For both ways, I get the same error:

(py35) ✔ ~/.../sgp-gsadjust/main_code [master|…10] 
14:35 $ python GSadjust.py 
Traceback (most recent call last):
  File "GSadjust.py", line 155, in <module>
    ctypes.windll.kernel32.SetDllDirectoryW(':\Shared\current\python\Miniconda3\envs\pyg35\Library\bin')
AttributeError: module 'ctypes' has no attribute 'windll'

What can be done about this and how can it be solved?

I am running ubuntu 16.04 (LTS).
Thanks!

**Comment by jkennedy-usgs** [comment]
Thanks for being the beta tester on linux :)  I've only tested on Mac/PC but I think that error is related to a missing Qt dll file. Let me look into it.

**Comment by jkennedy-usgs** [comment]
I removed the ctypes import and function calls. They were there for Pyinstaller to generate a standalone Windows .exe, which is no longer supported. I tested it on a EC2 instance over X11/SSH, it seemed to work. It will load the CG-6 test data in the FieldData directory.

**Comment by marcianito** [comment]
I can confirm that this new update lets me start GSadjust! Thanks for the fix! It starts a little slow but I will do some general testing (as this very linux beta tester) and then come back with some comments. :)
