### ISSUE TITLE
warnings on start of program

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#95]
On starting the program, the following warnings are shown in the terminal:

`gsadjust/GSadjust.py:515: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if open_type is not 'CG5':`
`gsadjust/GSadjust.py:572: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if fname[-1] is 'p':`

  Just for letting you know for future versions..

**Comment by jkennedy-usgs** [comment]
fixed in upcoming v1.0, thanks
