### ISSUE TITLE
some minor errors in documentation of example "complete"

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#98]
While going through the example data and workflow of example "complete", I found the following minor mistakes:

  - Second loop of first survey described to load should be the BURRIS B108 data from 2017, not 2018, right?
  - in the docu of the example, in section "8. Perform adjustment", first sentence the word "adjustment" is written twice.
  - after carrying out all fine-tuning, for me the chi-test for the survey "2017-12-05" is still not accepted.

**Comment by jkennedy-usgs** [comment]
Items addressed in the update help document.
