### ISSUE TITLE
bug (?) in function "import_abs_g_complete" - return values are empty

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#99]
I was not able to load data for absolute gravity measurements, using the "complete g" method.
I am using the latest commit of the repo.

So I dug a little deeper in the code of the function and found two things:

**First**, the separator is not "," but "\t".
**Second**, only if-statement checking if all index-numbers were set correctly always returned false, so there was no data actually loaded from the line-readings.

Solution: I changed line 430 of file "data_import.py" (see below), formatted the file with "\t" as a separator and everything worked fine!

`#  if all([g_idx, n_idx, s_idx, d_idx, th_idx]):`
`if "g_idx" and "n_idx" and "s_idx" and "d_idx" and "th_idx" in locals():`

**Comment by jkennedy-usgs** [comment]
Fixed in upcoming v 1.0, thanks
